#instance:
#    hostname: localhost
# http://localhost:8761/eureka/
# ${SERVICE_URL_DEFAULT_ZONE}

eureka:
  client:
    service-url:
      defaultZone: ${SERVICE_URL_DEFAULT_ZONE}

name:
  value: kalilmvp

spring:
  sleuth:
    sampler:
      probability: 1

management:
  endpoints:
    web:
      exposure:
        include: "*"

logstash:
  host: localhost
  port: 5000
  queue-size: 512
