eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

name:
  value: kalilmvp

spring:
  sleuth:
    sampler:
      probability: 1

management:
  endpoints:
    web:
      exposure:
        include: "*"
